#!/bin/sh
# chkconfig: 123456 90 10
# Samil Inverter data uploader service to PVupload.org
#
# Author: Christian Leyer

workdir=/opt/solar

start() {
    cd $workdir
    /usr/bin/python3 $workdir/samil_upload.py > /dev/null &
    echo "Samil Upload Service started.        \033[0;32m[OK]\033[0m"
}

stop() {
    pid=`ps -ef | grep "[p]ython3 $workdir/samil_upload.py" | \
        awk '{ print $2 }'`
    if [ ! -z "$pid" ]
    then
        echo $pid
        kill $pid
        sleep 2
    fi
    echo "Samil Upload Service stopped.        \033[0;32m[OK]\033[0m"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/samilupload {start|stop|restart}"
    exit 1
esac
exit 0
