#!/bin/sh
# chkconfig: 123456 90 10
# Samil Inverter upload service to PVoutput.org
# Init script for CentOS / RedHat systems
# Last change: 17.07.2016
# Author: Christian Leyer

. /etc/init.d/functions

# Configuration
NAME=samil_upload.py
DESC="Samil Upload Service"
SERVICE=samilupload
WORKDIR=/opt/solar         # Modify this to point to the install directory
DAEMON=$WORKDIR/$NAME
DAEMON_ARGS=""
LOG=/dev/null
#LOG=/var/log/$SERVICE.log  # Uncomment this if you want to store logs

PATH=/usr/local/bin:sbin:/usr/sbin:/bin:/usr/bin

start() {
    cd $WORKDIR
    python3 $DAEMON >$LOG &
    echo -e $DESC" started.\t\t\t\t   [  \033[0;32mOK\033[0m  ]"
}

stop() {
    pid=`ps -ef | grep '[p]ython3 '$DAEMON | awk '{ print $2 }'`
    kill $pid
    sleep 2
    echo -e $DESC" stopped.\t\t\t\t   [  \033[0;32mOK\033[0m  ]"
}

status() {
    pid=`ps -ef | grep '[p]ython3 '$DAEMON | awk '{ print $2 }'`
    if [ -z "$pid" ]; then
        echo -e $DESC" [Status: \033[0;31mSTOPPED\033[0m]\n"
    else
        echo -e $DESC" [Status: \033[0;32mRUNNING\033[0m] - PID: "$pid"\n"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/"$SERVICE" {start|stop|restart|status}"
        exit 1
esac
exit 0
